const GET_DOGS = "GET_DOGS";
const GET_DOG_BY_ID = "GET_DOG_BY_ID";
const GET_DOG_BY_NAME = "GET_DOG_BY_NAME";
const POST_DOG = "POST_DOG";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const TEMPERAMENTS_FILTER = "TEMPERAMENTS_FILTER";
const CREATED_FILTER = "CREATED_FILTER";
const ORDER_RESULT = "ORDER_RESULT";
const LIMPIAR_FILTROS = "LIMPIAR_FILTROS";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SEARCHED = "SEARCHED";
const ERROR = "ERROR";
const CLEAN_DETAIL = "CLEAN_DETAIL";
const CURRENT = "CURRENT";

export {
  GET_DOG_BY_ID,
  GET_DOGS,
  GET_DOG_BY_NAME,
  POST_DOG,
  GET_TEMPERAMENTS,
  TEMPERAMENTS_FILTER,
  CREATED_FILTER,
  ORDER_RESULT,
  LIMPIAR_FILTROS,
  SET_CURRENT_PAGE,
  SEARCHED,
  ERROR,
  CLEAN_DETAIL,
  CURRENT,
};
